openapi: 3.0.0
info:
  title: api
  version: '1.0'
  contact:
    name: MediGroove
  description: サンプルAPI
servers:
  - url: 'http://localhost:1323'
paths:
  '/test/{id}':
    parameters:
      - schema:
          type: integer
          format: int32
        name: id
        in: path
        required: true
    get:
      summary: サンプルGET
      tags:
        - sample
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Data'
        '404':
          description: Not Found
      operationId: get-test-id
      description: サンプルGET
    put:
      summary: サンプルPUT
      operationId: put-test-id
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Data'
      description: サンプルPUT
      tags:
        - sample
      security:
        - BasicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Data'
    delete:
      summary: サンプルDELETE
      operationId: delete-test-id
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      description: サンプルDELETE
      security:
        - BasicAuth: []
      tags:
        - sample
tags:
  - name: sample
    description: サンプル
components:
  schemas:
    Data:
      title: Data
      type: object
      x-examples:
        example-1:
          id: -2147483648
          value: string
      properties:
        id:
          type: integer
          format: int32
        value:
          type: string
        data2:
          $ref: '#/components/schemas/SubData'
        data3:
          $ref: '#/components/schemas/SubData'
      required:
        - id
        - data2
    SubData:
      title: SubData
      x-stoplight:
        id: 01c0b14e3ff8d
      type: object
      properties:
        id:
          type: string
        number:
          type: integer
      required:
        - id
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
