/*
    * api
    *
* Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package sampleapi

import (
	"github.com/Media-Groove/openapi-go-echo/openapi"
	"github.com/labstack/echo/v4"
)

// SampleApiRouter defines the required methods for binding the api requests to a responses for the SampleApi
// The SampleApiRouter implementation should parse necessary information from the http request,
// pass the data to a SampleApiServicer to perform the required actions, then write the service results to the http response.
type SampleApiRouter interface {
	DeleteTestId(ec echo.Context) error
	GetTestId(ec echo.Context) error
	PutTestId(ec echo.Context) error
}

// SampleApiServicer defines the api actions for the SampleApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type SampleApiServicer interface {
	DeleteTestId(*openapi.EchoContext, int32) (int, interface{})
	GetTestId(*openapi.EchoContext, int32) (int, interface{})
	PutTestId(*openapi.EchoContext, int32, *Data) (int, interface{})
}
