/*
    * api
    *
* Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package sampleapi

import (
	"errors"
	"net/http"

	"github.com/Media-Groove/openapi-go-echo/openapi"
)

// SampleApiService is a service that implements the logic for the SampleApiServicer
// This service should implement the business logic for every endpoint for the SampleApi API.
// Include any external packages or services that will be required by this service.
type SampleApiService struct {
}

// NewSampleApiService creates a default api service
//noinspection GoUnusedExportedFunction
func NewSampleApiService() SampleApiServicer {
	return &SampleApiService{}
}

// DeleteTestId - サンプルDELETE
//noinspection GoUnusedParameter
func (s *SampleApiService) DeleteTestId(ec *openapi.EchoContext, id int32) (int, interface{}) {
	// TODO - update DeleteTestId with the required logic for this service method.
	// Add api_sample_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response 204, {}) or use other options such as http.Ok ...
	//return 204, nil

	//TODO: Uncomment the next line to return response 404, {}) or use other options such as http.Ok ...
	//return 404, nil

	return http.StatusNotImplemented, errors.New("DeleteTestId method not implemented")
}

// GetTestId - サンプルGET
//noinspection GoUnusedParameter
func (s *SampleApiService) GetTestId(ec *openapi.EchoContext, id int32) (int, interface{}) {
	// TODO - update GetTestId with the required logic for this service method.
	// Add api_sample_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response 200, Data{} or use other options such as http.Ok ...
	//return 200, Data{}

	//TODO: Uncomment the next line to return response 404, {}) or use other options such as http.Ok ...
	//return 404, nil

	return http.StatusNotImplemented, errors.New("GetTestId method not implemented")
}

// PutTestId - サンプルPUT
//noinspection GoUnusedParameter
func (s *SampleApiService) PutTestId(ec *openapi.EchoContext, id int32, data *Data) (int, interface{}) {
	// TODO - update PutTestId with the required logic for this service method.
	// Add api_sample_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response 201, Data{} or use other options such as http.Ok ...
	//return 201, Data{}

	return http.StatusNotImplemented, errors.New("PutTestId method not implemented")
}
