/*
    * api
    *
* Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package sampleapi

type Data struct {
	Id int32 `json:"id"`

	Value *string `json:"value"`

	Data2 SubData `json:"data2"`

	Data3 *SubData `json:"data3"`
}
