openapi: 3.0.0
info:
  contact:
    name: MediGroove
  description: サンプルAPI
  title: api
  version: "1.0"
servers:
- url: http://localhost:1323
tags:
- description: サンプル
  name: sample
paths:
  /test/{id}:
    delete:
      description: サンプルDELETE
      operationId: delete-test-id
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      security:
      - BasicAuth: []
      summary: サンプルDELETE
      tags:
      - sample
    get:
      description: サンプルGET
      operationId: get-test-id
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Data'
          description: OK
        "404":
          description: Not Found
      summary: サンプルGET
      tags:
      - sample
    put:
      description: サンプルPUT
      operationId: put-test-id
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Data'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Data'
          description: Created
      security:
      - BasicAuth: []
      summary: サンプルPUT
      tags:
      - sample
components:
  schemas:
    Data:
      example:
        data3:
          number: 6
          id: id
        data2:
          number: 6
          id: id
        id: 0
        value: value
      properties:
        id:
          format: int32
          type: integer
        value:
          type: string
        data2:
          $ref: '#/components/schemas/SubData'
        data3:
          $ref: '#/components/schemas/SubData'
      required:
      - data2
      - id
      title: Data
      type: object
      x-examples:
        example-1:
          id: -2147483648
          value: string
    SubData:
      example:
        number: 6
        id: id
      properties:
        id:
          type: string
        number:
          type: integer
      required:
      - id
      title: SubData
      type: object
      x-stoplight:
        id: 01c0b14e3ff8d
  securitySchemes:
    BasicAuth:
      scheme: basic
      type: http
