version: '3.5'

services:
  # Go echo サーバ
  go-echo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sample-go-echo
    tty: true
    volumes:
      - ..:/usr/src:delegated
    ports:
      - 1323:1323 # echoサーバの待受ポート
    networks:
      - openapi-network
  # swagger-ui
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: sample-swagger-ui
    volumes:
      - ../_openapi/sample:/usr/share/nginx/html/sample
    ports:
      - 8080:8080
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/sample/api.v1.yaml
    networks:
      - openapi-network

networks:
  openapi-network:
    name: openapi-network
